# Generated by Django 5.1.7 on 2025-03-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('home_services_card_name', models.CharField(max_length=50)),
                ('home_services_card_description', models.CharField(max_length=250)),
                ('home_discover_name', models.CharField(max_length=50)),
                ('home_discover_role', models.CharField(max_length=50)),
                ('home_discover_image', models.ImageField(upload_to='media')),
                ('home_blog_role', models.CharField(max_length=50)),
                ('home_blog_image', models.ImageField(upload_to='media')),
                ('home_blog_description', models.TextField(max_length=200)),
            ],
        ),
    ]
