# Generated by Django 3.2.25 on 2025-04-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erfanian_extraction', '0002_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_blog_name', models.CharField(max_length=100)),
                ('about_blog_image', models.ImageField(upload_to='media')),
                ('about_blog_description', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='HomeBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_blog_role', models.CharField(max_length=50)),
                ('home_blog_image', models.ImageField(upload_to='media')),
                ('home_blog_description', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Home Blogs',
            },
        ),
        migrations.CreateModel(
            name='HomeDiscover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_discover_name', models.CharField(max_length=50)),
                ('home_discover_role', models.CharField(max_length=50)),
                ('home_discover_image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Home Discoveries',
            },
        ),
        migrations.CreateModel(
            name='HomeServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_services_card_name', models.CharField(max_length=50)),
                ('home_services_card_description', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Home Services',
            },
        ),
        migrations.CreateModel(
            name='Our_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_image', models.ImageField(upload_to='media')),
                ('team_name', models.CharField(max_length=50)),
                ('team_role', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Our Teams',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_image', models.ImageField(upload_to='media')),
                ('portfolio_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Porfolios',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_service_name', models.CharField(max_length=100)),
                ('services_service_description', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServicesGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_gallery_image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Services Gallary',
            },
        ),
        migrations.DeleteModel(
            name='About_Us',
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home'},
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_blog_description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_blog_image',
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_blog_role',
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_discover_image',
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_discover_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_discover_role',
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_services_card_description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_services_card_name',
        ),
    ]
