# Generated by Django 5.1.7 on 2025-04-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erfanian_extraction', '0003_auto_20250402_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
