# Generated by Django 5.1.7 on 2025-04-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erfanian_extraction', '0004_aboutusprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('project_scope', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutusprojects',
            options={'verbose_name_plural': 'About Our Projects'},
        ),
    ]
